

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/database:/app/database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
